#========================================
# server configuration
#========================================
server:
  port: 9889

#================================
#  h2 Database configuration
#================================
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
#=============================================
#  oracle Database configuration 
#=============================================

#spring:
#  datasource:
#    driverClassName: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:orcl
#    username: scott
#    password: tiger
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.Oracle10gDialect
#    show-sql: true
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
#============================================
#    SMTP Configuration
#============================================
  mail:
    host: smtp.gmail.com
    port: 587
    username: aftabhashim04@gmail.com
    password: 9123134902
    protocol: smtp
#        tls: true
    properties:
      mail:
        smtp: 
          auth: true
          starttls.enable: true
          ssl.trust: smtp.gmail.com
